export const USER_SIGNIN_API = "USER_SIGNIN_API"

// -------------- LOGIN ----------------
export const USLOGIN = "USLOGIN"


// --------------- GET_PROJECT_CATEGORY---
export const GET_ALL_PROJECT_CATEGORY = "GET_ALL_PROJECT_CATEGORY"
export const GET_ALL_PROJECT_CATEGORY_SAGA = "GET_ALL_PROJECT_CATEGORY_SAGA"


// ---------------- DRAWER POPUP --------
export const OPEN_DRAWER = "OPEN_DRAWER"
export const CLOSE_DRAWER = "CLOSE_DRAWER"
export const OPEN_EDIT_FORM_PROJECT = "OPEN_EDIT_FORM_PROJECT"
export const SET_EDIT_FORM_PROJECT = "SET_EDIT_FORM_PROJECT"

// --------------- PROJECT EDIT ------------
export const GET_EDIT_PROJECT = "GET_EDIT_PROJECT"
export const UPDATE_EDIT_PROJECT = "UPDATE_EDIT_PROJECT"
export const UPDATE_EDIT_PROJECT_SAGA = "UPDATE_EDIT_PROJECT_SAGA"